---
kind: pipeline
name: node10-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: arm64v8/node:10
  commands:
  - apt-get update
  - apt-get install -y opam zip
  - opam init
  - eval $(opam config env)
  - opam switch install 4.05.0
  - eval $(opam config env)
  - opam pin add flowtype . -n
  - opam depext -u flowtype
  - opam install flowtype --deps-only
  - opam install js_of_ocaml 
  - eval $(opam config env)
  - make all
  - ./bin/flow --help
  - zip ./bin/flow ./bin/flow-linux-arm64.zip
  
- name: publish
  image: plugins/github-release
  settings:
    api_key: 33b51744caf1dc73335bed0a77b779a2e51602c0
    files: bin/flow-linux-arm64.zip
  when:
    event: tag
